### ISSUE TITLE
Windows Support

### ISSUE THREAD

**Issue by bybrtybwterwybertybwetr** [RevoltSecurities/SubProber#6]
Currently subprober uses uvloop, which does not support windows users.
A similar library is [winloop](https://github.com/Vizonex/Winloop), which is specifically designed to work with windows.
A simple platform check to switch between the 2 couple be very useful to allow windows compatibility.

Here's A small Example of using winloop when uvloop is not available to us
```
import sys
import aiohttp
import asyncio

async def main():
    async with aiohttp.ClientSession("https://httpbin.org") as client:
        async with client.get("/ip") as resp:
            print(await resp.json())

if __name__ == "__main__":
    #if user is on a windows platform
    if sys.platform in ('win32', 'cygwin', 'cli'): 
        from winloop import run
    else: 
        # if we're on apple use uvloop instead
        from uvloop import run
    run(main())
```

**Comment by RevoltSecurities** [comment]
Hi @bybrtybwterwybertybwetr  ,
We already aware of this issue and we patched in version `v2.0.0` and this is latest version of subprober, so we request you to update subprober to its latest version . 

Kind regards, 
@RevoltSecurities
