### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by mrwhitedon22** [RevoltSecurities/SubProber#8]
[INFO]: Import Error occured in Module imports due to: No module named 'distutils'
[INFO]: If you are encountering this issue more than a time please report the issues in Subprober Github page..

**Comment by RevoltSecurities** [comment]
Hello @RevoltSecurities ,
We request you to update your python and pip to its latest version and try again and I hope this will resolve your issue, if your issue still persist please reply with the error again. 

Kind regards,
@RevoltSecurities
